### ISSUE TITLE
Missing invoked arn in Sam throwing error

### ISSUE THREAD

**Issue by lefthand** [DataDog/datadog-lambda-rb#45]
## Expected Behavior
I am trying to test my functions that use this layer locally using AWS Sam. 

## Actual Behavior
When Sam executes the function I get an error from this line: https://github.com/DataDog/datadog-lambda-rb/blob/c15f0f0916c90123416dc44e7d6800ef4a7cfdbf/lib/datadog/lambda/trace/listener.rb#L59

I found that `context.invoked_function_arn` is set to `nil`.

## Steps to Reproduce the Problem

  1. Create a new Sam function with `sam init`. I used the Ruby 2.7 hello world example function.
  1. Wrap the code in the Datadog Lambda layer
  1. Run `sam local invoke "HelloWorldFunction" --no-event`

## Specifications

  - Datadog Lambda Layer version: 1.12 (other version also throw this error)
  - Ruby version: 2.7 or 2.5
  - Sam version: 1.18.0 (also tried with 1.15.0)
  
## Stacktrace
  
  ```
{
  "errorMessage": "undefined method `downcase' for nil:NilClass",
  "errorType": "Function<NoMethodError>",
  "stackTrace": [
    "/opt/ruby/gems/2.7.0/gems/datadog-lambda-1.12.0/lib/datadog/lambda/trace/listener.rb:59:in `get_option_tags'",
    "/opt/ruby/gems/2.7.0/gems/datadog-lambda-1.12.0/lib/datadog/lambda/trace/listener.rb:40:in `on_wrap'",
    "/opt/ruby/gems/2.7.0/gems/datadog-lambda-1.12.0/lib/datadog/lambda.rb:57:in `wrap'",
    "/var/task/app.rb:19:in `lambda_handler'"
  ]
}
  ```

I tried several different local execution environments on different hosts and as far as I can tell, `context.invoked_function_arn` isn't ever set when running via Sam. I don't believe this was true in the past, and I can't find any specific change that is causing this.

**Comment by tianchu** [comment]
@lefthand Thanks for the bug report, I think this can be fixed by defaulting `function_arn` to an empty string like in the [Python library](https://github.com/DataDog/datadog-lambda-python/blob/0affcc2a883b003679263f743979419a496bcdc2/datadog_lambda/tracing.py#L329). Since you already found the issue and it probably only require a small change, do you mind [contributing a PR](https://github.com/DataDog/datadog-lambda-rb/blob/main/CONTRIBUTING.md) 🙇‍♂️ ?

**Comment by pjdavis** [comment]
As a workaround, before I invoke the `Datadog::Lambda.wrap` block, i've added this: 

```
  if context.invoked_function_arn.nil?
    context.instance_variable_set('@invoked_function_arn', '')
  end
  ```
  
Working on getting a PR up with a fix, but having some trouble with my local setup getting it tested. Hopefully I'll have some time tomorrow to see if I can get a PR up for it, though.

**Comment by lefthand** [comment]
Thanks @pjdavis, that solved the problem for me for now. I'll keep an eye out for your PR.

**Comment by maxday** [comment]
(#51) should fix this issue
