### ISSUE TITLE
Ruby 3.3 support

### ISSUE THREAD

**Issue by psimms-r7** [DataDog/datadog-lambda-rb#90]
## Expected Behavior

Hi

Is there plans to support ruby 3.3

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Datadog Lambda Layer version: 
  - Ruby version:  
  
## Stacktrace
  
  ```
  Paste here
  ```

**Comment by duncanista** [comment]
Hey @psimms-r7,

Yes, there is!
Sorry we haven't done it as promptly as expected.

I'll share this issue with the team and make sure we can have support as soon as possible.

**Comment by wildodecisiv** [comment]
Hey @duncanista ! 
Is there any estimate date to release the layer supporting Ruby 3.3? :)

**Comment by alexgallotta** [comment]
Hi @wildodecisiv ! Unfortunately we don't have bandwidth for this at this moment, but we strongly encourage open source contributions! If you have some ruby expertise and want to give it a short, we are happy to provide guidance and review

**Comment by wildodecisiv** [comment]
> Hi @wildodecisiv ! Unfortunately we don't have bandwidth for this at this moment, but we strongly encourage open source contributions! If you (or anyone else interested) have some ruby expertise and want to give it a try, we are happy to provide guidance and review

Here is the pr Alex https://github.com/DataDog/datadog-lambda-rb/pull/92, hope I can get some support to have this ready for merge!

**Comment by alexgallotta** [comment]
That's great! Amazing job, @duncanista will follow up there!

**Comment by duncanista** [comment]
I deeply apologize for not having this earlier.

We appreciate truly your contributions that helped us release this quicker.

Please find the latest release `v23` ([v2.23.0](https://github.com/DataDog/datadog-lambda-rb/releases/tag/v2.23.0)) supporting the latest version of the available tracer in `ddtrace`, as well as support for Ruby 3.3.

Thank you!
